List<String> acceptedCategories = [
  "Animal Kingdom",
  "Books & Literature",
  "Film",
  "Games",
  "General Knowledge",
  "Geography",
  "History",
  "Maths",
  "Music",
  "Natural World",
  "Politics",
  "Pop Culture",
  "Science",
  "Sports",
  "Technology",
  "Television",
];
